CREATE TABLE FSRV_MINS (
    SEQ_ID int NOT NULL,
    MIN_FIRST decimal(16,2) NOT NULL,
    MIN_NXT decimal(16,2) NOT NULL,
    MIN_SELL decimal(16,2) NOT NULL,
    MIN_SW decimal(16,2) NOT NULL,
    MIN_TRSF decimal(16,2) NOT NULL,
    MIN_BAL decimal(16,2) NOT NULL,
    MIN_PAC decimal(16,2) NOT NULL,
    MIN_SWP decimal(16,2) NOT NULL, 
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_ELIG_PROV(
    SEQ_ID int NOT NULL,
    PROV_STATE char(2) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_prod(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_ELIG_TRXN (
    SEQ_ID int NOT NULL,
    TRXN_TYPE char(2) NOT NULL,
    TRXN_STATUS char(1) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_ELIG_ACCT_TYPES (
    SEQ_ID int NOT NULL,
    DESIGNATION char(1) NOT NULL,
    ACCT_TYPE char(3) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_ELIG_DIV_OPT (
    SEQ_ID int NOT NULL,
    DIV_FREQ char(1) NOT NULL,
    DIV_OPT_1 char(1) NOT NULL,
    DIV_OPT_4 char(1) NOT NULL,
    DIV_OPT_5 char(1) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;

CREATE TABLE FSRV_PROD_MODEL (
    SEQ_ID int NOT NULL,
    TYPE char(6) NOT NULL,
    FREQ char(1) NOT NULL,
    SETTLE_PERIOD int NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;