CREATE TABLE FSRV_MINS (
    SEQ_ID int NOT NULL,
    MIN_FIRST decimal(16,2) NOT NULL,
    MIN_NXT decimal(16,2) NOT NULL,
    MIN_SELL decimal(16,2) NOT NULL,
    MIN_SW decimal(16,2) NOT NULL,
    MIN_TRSF decimal(16,2) NOT NULL,
    MIN_BAL decimal(16,2) NOT NULL,
    MIN_PAC decimal(16,2) NOT NULL,
    MIN_SWP decimal(16,2) NOT NULL, 
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;
