CREATE TABLE FSRV_ELIG_DIV_OPT (
    SEQ_ID int NOT NULL,
    DIV_FREQ char(1) NOT NULL,
    DIV_OPT_1 char(1) NOT NULL,
    DIV_OPT_4 char(1) NOT NULL,
    DIV_OPT_5 char(1) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
);