CREATE TABLE FSRV_ELIG_ACCT_TYPES (
    SEQ_ID int NOT NULL,
    DESIGNATION char(1) NOT NULL,
    ACCT_TYPE char(3) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;