CREATE TABLE FSRV_FD_FILE_HIST (
    SEQ_ID int NOT NULL AUTO_INCREMENT,
    FILE_NAME char NOT NULL,
    VERSION char NOT NULL,
    DATE NOT NULL,
    TIME NOT NULL,
    LOAD_DATETIME datetime NOT NULL,
);