CREATE TABLE FSRV_ELIG_TRXN (
    SEQ_ID int NOT NULL,
    TRXN_TYPE char(2) NOT NULL,
    TRXN_STATUS char(1) NOT NULL,
    FOREIGN KEY (SEQ_ID) REFERENCES FSRV_PROD(FSRV_ID)
) DEFAULT CHARSET = utf8;