CREATE TABLE FSRV_PROD (
    FSRV_ID int NOT NULL auto_increment,
    MGMT_CODE char(3) NOT NULL,
    EFF_DT date NOT NULL,
    FUND_ID char(5) NOT NULL,
    FUND_LINK_ID char(5) NOT NULL,
    CUT_OFF_TIME time NOT NULL,
    CUSIP char(9),
    ISIN char(12),
    MGMT_CO_BRAND_NM char(7) NOT NULL,
    ENG_SHORT_NM char(20) NOT NULL,
    ENG_LONG_NM char(80) NOT NULL,
    FRE_SHORT_NM char(20) NOT NULL,
    FRE_LONG_NM char(80) NOT NULL,
    PROD_TYPE char(1) NOT NULL,
    CURR char(2) NOT NULL,
    LOAD_TYPE char(4) NOT NULL,
    CLASSIFICATION char(2),
    TAX_STRUCT char(1) NOT NULL,
    MM_FLAG char(1) NOT NULL,
    BARE_TRUSTEE_FLAG char(1) NOT NULL,
    RISK_CLASS char(1) NOT NULL,
    ACCT_SETUP_FEE decimal(16,2) NOT NULL,
    SERV_FEE_RATE decimal(16,3) NOT NULL,
    SERV_FEE_FREQ char(1) NOT NULL,
    DSC decimal(16,3),
    DSC_DURATION int,
    MAX_COMM decimal(16,3) NOT NULL,
    MAX_SW_COMM decimal(16,3) NOT NULL,
    NEGOT_FEE char(1),
    NEGOT_TRAILER char(1),
    FEE_BASED_ELIG char(1),
    SERIES char(5),
    CLASS char(5),
    SER_CLASS_SEQ_IN_NAME char(2),
    BRAND char(15),
    DISC_BROKER_ONLY char(1),
    REG_DOC_TYPE char(1) NOT NULL,
    ELIG_US char(1) NOT NULL,
    ELIG_OFFSHORE char(1) NOT NULL,
    ELIG_PAC char(1) NOT NULL,
    ELIG_SWP char(1) NOT NULL,
    PRIMARY KEY(FSRV_ID)
) DEFAULT CHARSET = utf8;